const actionTypes = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  GET_POSTS: 'GET_POSTS',
  GET_POSTS_LIMIT: 'GET_POSTS_LIMIT',
  GET_NEW_POST: 'GET_NEW_POST',

  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_PRICES: 'GET_PRICES',
  GET_AREAS: 'GET_AREAS',
  GET_PROVINCES: 'GET_PROVINCES'
};

export default actionTypes;
